swagger: "2.0"
info:
  description: "the is psichologist service"
  version: "1.0.0"
  title: "psychologsitsvc"
  contact:
    email: "farexy@yandex.ru"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:9998"
basePath: "/api/v1"
tags:
- name: "psychologist"
  description: 'endpoints mainly necessary for a psychologist'
- name: "admin"
  description: 'endpoints onli operator (admin role)'
- name: "client"
  description: 'endpoints mainly necessary for a client'
schemes:
- "http"
paths:
  /employees/{employee_id}/clients/name:
    get:
      tags:
      - "psychologist"
      summary: "Get a list of your customer names."
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "customer id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: '#/definitions/client'
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /employees/list:
    get:
      tags:
      - "admin"
      summary: "list of psychologists and their id clients"
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: '#/definitions/response_employees_list'
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /lessons/list:
    get:
      tags:
      - "admin"
      summary: "All classes, psychologists and attached clients"
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: '#/definitions/response_lesson_list'
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /employees/list_by_id:
    post:
      tags:
      - "admin"
      summary: "list of psychologists"
      description: ""
      parameters:
        - in: header
          name: X-User-Role
          description: "user role"
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            items:
              $ref: '#/definitions/request_client_list_by_id'
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: '#/definitions/psychologist'
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /lessons/client/employee/{employee_id}/dateteme/{date_time}/delete:
    delete:
      tags:
      - "admin"
      summary: "list of psychologists"
      description: ""
      parameters:
        - in: header
          name: X-User-Role
          description: "user role"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "customer id"
          required: true
          type: string
        - name: date_time
          in: path
          description: "date and time lesson (URL encoding)"
          required: true
          type: string
          format: date-time 
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /employees/{employee_id}/name:
    get:
      tags:
      - "client"
      summary: "The name of the psychologist"
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "customer id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: '#/definitions/psychologist'
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /employees/{employee_id}/client/{client_id}/lessons:
    get:
      tags:
      - "client"
      summary: "Lessons by employee id and cleint id"
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "employee id"
          required: true
          type: string
        - name: client_id
          in: path
          description: "client id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: '#/definitions/schedule'
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /employees/{employee_id}/clients/lessons:
    get:
      tags:
      - "psychologist"
      summary: "Get a list of your classes: date, customer name."
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "customer id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
              $ref: "#/definitions/response_employee_clients_lessons"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /employees/{employee_id}/clients/{client_id}/lessons/datetime/{date_time}/set:
    post:
      tags:
      - "psychologist"
      summary: "Schedule an activity with your client."
      description: "Recording is possible at any time, including non-working"
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: client_id
          in: path
          description: "customer id"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "employee id"
          required: true
          type: string
        - name: date_time
          in: path
          description: "date and time lesson (URL encoding)"
          required: true
          type: string
          format: date-time     
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/response400"
  /employees/{employee_id}/clients/{client_id}/lessons/datetime/{date_time}/reschedule/datetime/{new_date_time}/set:
    put:
      tags:
      - "psychologist"
      summary: "Reschedule your occupation."
      description: "Transfer is possible at any time, including non-working."
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: client_id
          in: path
          description: "customer id"
          required: true
          type: string
        - name: employee_id
          in: path
          description: "employee id"
          required: true
          type: string
        - name: date_time
          in: path
          description: "date and time lesson (URL encoding)"
          required: true
          type: string
          format: date-time
        - name: new_date_time
          in: path
          description: "what date and time the lesson is postponed (URL encoding)"
          required: true
          type: string
          format: date-time  
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/response400"
            
definitions:
  psychologist:
    type: object
    description: Presents model psychlogist
    properties:
      id:
        type: string
        default: "psychologist id"
        example: "90a486-8e73-4c31-b10f-c7f24c115cdd"
      family_name:
        type: string
        default: "psychologist fmalily name"
        example: "Garvetov"
      name:
        type: string
        default: "psychologist name"
        example: "Sergey"
      patronomic:
        type: string
        default: "psychologist patronomic"
        example: "Andreevich"
  lesson_list:
    type: "object"
    description: "Presents lesson"
    properties:
      date_time:
        type: string
        format: date-time
        example: "2020-03-31T13:00:00Z"
        description: "date time lesson"
  client:
    type: "object"
    description: "Presents client"
    properties:
      id:
        type: string
        description: "id client"
        example: "48faa486-8e73-4c31-b10f-c7f24c115cda"
      family_name:
        type: string
        description: "family name"
        example: "Gusev"
      name:
        type: string
        description: "name"
        example: "Evgeniy"
      patronomic:
        description: "pathornomic"
        example: "Victorovich"
        type: string
  schedule:
    type: object
    description: presetnst schedule
    properties:
      data_time:
        type: string
        format: date-time
        description: date time lesson
        example: '2020-03-31T13:00:00+07:00'
  request_client_list_by_id:
    type: object
    properties:
      id:
        type: string
        description: "customet id"
        example: "48faa486-8e73-4c31-b10f-c7f24c115cda"
  response_employee_clients_lessons:
    type: array
    items:
      properties:
        client:
          type: array
          items:
            $ref: '#/definitions/client'
        schedule:
          type: array
          items:
            $ref: '#/definitions/schedule'
  response_lesson_list:
    type: array
    items:
      properties:
        client:
          type: array
          items:
            $ref: '#/definitions/client'
        schedule:
          type: array
          items:
            properties:
              employee:
                type: object
                properties:
                  id:
                    type: string
                    description: "id client"
                    example: "48faa486-8e73-4c31-b10f-c7f24c115cda"
                  family_name:
                    type: string
                    description: "family name"
                    example: "Gusev"
                  name:
                    type: string
                    description: "name"
                    example: "Evgeniy"
                  patronomic:
                    description: "pathornomic"
                    example: "Victorovich"
                    type: string
              date_time:
                type: string
                format: date-time
                description: date time lesson
                example: '2020-03-31T13:00:00Z'
                
      
  response_employees_list:
    type: object
    description: represents the subscologist and a list of his clients (identifiers)
    properties:
      id:
        type: string
        default: "psychologist id"
        example: "90a486-8e73-4c31-b10f-c7f24c115cdd"
      family_name:
        type: string
        default: "psychologist fmalily name"
        example: "Garvetov"
      name:
        type: string
        default: "psychologist name"
        example: "Sergey"
      patronomic:
        type: string
        default: "psychologist patronomic"
        example: "Andreevich"
      clients:
        type: array
        items:
            properties:
              id:
                type: string
                description: "client id"
                example: "50faa486-8e73-4c31-b10f-c7f24c115cda"
  response400:
    type: "object"
    properties:
      error:
        type: "string"
        example: "a lesson can only be scheduled at the beginning of the hour"
        description: "Error"
  response403:
    type: "object"
    properties:
      error:
        type: "string"
        example: "not valid X-User-Role"
        description: "Error"