version: "2.1"
services:
  psychologist-service:
    image: psychologist-service
    build:
      context: .
      dockerfile: psychologist/Dockerfile
    environment:
      - APP_ENV=local
    restart: always
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - 9998:9999
    depends_on:
      psychologist-db:
        condition: service_healthy

  psychologist-db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "psychologist"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
