database:
  log_queries: true
  timeout_seconds: 20
  dsn: "postgres://clients-db/clients?sslmode=disable&user=postgres&password=postgres"

server:
  port: :8081
  debug: true
  read_timeout_seconds: 15
  write_timeout_seconds: 20

user_roles: [client, admin, psychologist]

url_services:
  psychologist_svc_base_url: "http://psychologist-service:8081/api/v1"