swagger: "2.0"
info:
  description: "the is client service"
  version: "1.0.0"
  title: "clientsvc"
  contact:
    email: "farexy@yandex.ru"
  license:
    name: "MIT"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8082"
basePath: "/api/v1"
tags:
- name: "client"
- name: "psychologist"
- name: "admin"
  description: "Get info from psychologist \n"
schemes:
- "http"
paths:
  /client/{client_id}/lessons:
    get:
      tags:
      - "client"
      summary: "Get a list of your classes"
      description: "The client is always assigned one psychologist."
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: client_id
          in: path
          description: "customer id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: "#/definitions/lesson_list"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /client/{client_id}/psychologist/name:
    get:
      tags:
      - "client"
      summary: "Get the name of your psychologist."
      description: "The client is always assigned one psychologist."
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: client_id
          in: path
          description: "customer id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/psychologist"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /client/psychologist/{psychologist_id}/name:
    get:
      tags:
      - "psychologist"
      summary: "Get a list of clients by psychologist ID"
      description: "."
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: psychologist_id
          in: path
          description: "psychologist id"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: "#/definitions/client"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /client/{client_id}/lesson/{date_time}/set:
    post:
      tags:
      - "client"
      summary: "Sign up for a lesson to a psychologist."
      description: "The client is always assigned one psychologist.
       Recording is possible only for the working time of the psychologist"
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: client_id
          in: path
          description: "customer id"
          required: true
          type: string
        - name: date_time
          in: path
          description: "date and time lesson (URL encoding)"
          required: true
          type: string
          format: date-time     
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/response400"
  /client/{client_id}/lesson/{date_time}/reschedule/datetime/{new_date_time}/set:
    put:
      tags:
      - "client"
      summary: "Reschedule your occupation."
      description: "The client is always assigned one psychologist.
       Time transfer is possible only for the working time of the psychologist."
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
        - name: client_id
          in: path
          description: "customer id"
          required: true
          type: string
        - name: date_time
          in: path
          description: "date and time lesson (URL encoding)"
          required: true
          type: string
          format: date-time
        - name: new_date_time
          in: path
          description: "what date and time the lesson is postponed (URL encoding)"
          required: true
          type: string
          format: date-time  
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/response400"
  /client/list:
    get:
      tags:
      - "admin"
      summary: "List all clients"
      description: ""
      parameters:
        - name: X-User-Role
          in: header
          description: "user role"
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: "#/definitions/client"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
  /client/list_by_id:
    post:
      tags:
      - "admin"
      summary: "List all clients"
      description: ""
      parameters:
        - in: header
          name: X-User-Role
          description: "user role"
          required: true
          type: string
        - in: body
          name: "body"
          required: true
          schema:
            items:
              $ref: "#/definitions/request_client_list_by_id"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            items:
              $ref: "#/definitions/client"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/response403"
definitions:
  psychologist:
    type: object
    description: Presents model psychlogist
    properties:
      id:
        type: string
        default: "psychologist id"
        example: "48faa486-8e73-4c31-b10f-c7f24c115cda"
      family_name:
        type: string
        default: "psychologist fmalily name"
        example: "Gusev"
      name:
        type: string
        default: "psychologist name"
        example: "Evgeniny"
      patronomic:
        type: string
        default: "psychologist patronomic"
        example: "Victorovich"
  lesson_list:
    type: "object"
    description: "Presents lesson"
    properties:
      date_time:
        type: string
        format: date-time
        example: "2020-03-31T13:00:00Z"
        description: "date time lesson"
  client:
    type: "object"
    description: "Presents client"
    properties:
      id:
        type: string
        description: "id client"
        example: "48faa486-8e73-4c31-b10f-c7f24c115cda"
      family_name:
        type: string
        description: "family name"
        example: "Gusev"
      name:
        type: string
        description: "name"
        example: "Evgeniy"
      patronomic:
        description: "pathornomic"
        example: "Victorovich"
        type: string
  request_client_list_by_id:
    type: object
    properties:
      id:
        type: string
        description: "customet id"
        example: "48faa486-8e73-4c31-b10f-c7f24c115cda"   
  response400:
    type: "object"
    properties:
      error:
        type: "string"
        example: "a lesson can only be scheduled at the beginning of the hour"
        description: "Error"
  response403:
    type: "object"
    properties:
      error:
        type: "string"
        example: "not valid X-User-Role"
        description: "Error"